[Distribution]
Distribution=fedora
Release=43
Architecture=arm64

[Output]
Format=disk
Output=fedora43
SectorSize=512
CompressOutput=no

[Content]
Bootable=yes
Bootloader=systemd-boot
Autologin=yes
Hostname=comet
UnifiedKernelImages=no
KernelModulesInitrd=no
# Disable mkosi-generated initrd
Initrds=
Devicetree=freescale/imx8mp-mecha-comet.dtb
RootPassword=mecha
PostInstallationScripts=mkosi.postinst

# Include standard groups, they are defined at
# https://pagure.io/fedora-comps/blob/main/f/comps-f43.xml.in

Packages=
    @base-graphical
    @core
    @multimedia
    @networkmanager-submodules
    @standard
    @phosh-desktop
    @fonts
    @input-methods
    bluez
    cpufrequtils
    evtest
    google-noto-emoji-fonts
    google-noto-fonts-all
    gsettings-desktop-schemas
    htop
    i2c-tools
    impeller
    libgpiod-utils
    mechanix-extension-service
    mutter
    nano
    openssh-server
    sudo
    systemd
    systemd-boot-unsigned
    upower
    usbutils
    # vercel-geist-mono-fonts -> only available in testing for Fedora 43
    xdg-user-dirs
    xorg-x11-server-Xwayland

# Custom packages

Packages=
    nxp-firmware-1.0-1.fc43.aarch64
    kernel-6.12.20+mecha-2.aarch64
